### ISSUE TITLE
Moving the `usb-device` and `usbd-serial` crates to this organization

### ISSUE THREAD

**Issue by mvirkkunen** [rust-embedded-community/meta#15]
Hi,

I'm not currently interested in maintaining these crates, but it seems they're getting plenty of use which isn't an ideal combination. Other people have expressed interest in helping out with maintenance, but for that it'd be best if the code wasn't just under my personal GitHub account, but under an org. Would this organization be the best fit for a platform agnostic crate?

The reason I'm not interested in maintaining these at the moment is that they were my first real Rust project and I've learned a lot since, and my opinion is that they're due for a rewrite, which I want to do eventually. Before that however I want to see if async/await becomes the main way of doings things on embedded before changing the entire API, but that's still some time away, waiting for more issues to be resolved in Rust itself.

If you'd be willing to adopt these crates, I'd still like to retain commit access, how would we go about arranging that?

Thanks!

/ Matti

**Comment by eldruin** [comment]
Your explanation fits right into the mission of this org so I would welcome these crates. Them being platform-agnostic or not does not matter.
Since you said you are not interested in maintaining them, I think what would make most sense would be for you to transfer them and we just grant you privileges without you having to join the org.
You would need to grant privileges to a team of this org so that people can publish new versions to crates.io.

**Comment by mvirkkunen** [comment]
Sounds good!

How would I go about transferring the repositories? AFAIK I can't transfer to an organization I'm not a member of.

Also if you could mention which team needs access on crates.io, I can add it.

**Comment by mvirkkunen** [comment]
There you go!

**Comment by eldruin** [comment]
Alright the transfer is done now, thanks!
- [usb-device](https://github.com/rust-embedded-community/usb-device)
- [usbd-serial](https://github.com/rust-embedded-community/usbd-serial)

About the team permission issue I've had it in the past but cannot remember how I fixed it. The team is visible and crates.io has OAuth permission through me and no further restrictions.
It may be due to the fact that you are not a member of the team that is being added: https://github.com/rust-lang/crates.io/issues/1366
If so, would you invite me individually as owner in crates.io and then I can see how this can be sorted out?

**Comment by mvirkkunen** [comment]
I've sent you invites, let's see if that helps.

**Comment by eldruin** [comment]
Alright, that worked. I could invite the team and although it said only that it sent an invitation, the team appears as an owner in crates.io already.
Thanks and closing.
